apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weave-gitops-enterprise-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./platform
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
