apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: wge-key
  interval: 5m0s
  path: ./secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
