apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi-clusters
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/management/clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
